FROM node:12.16.2 as builder

# 작업 폴더를 만들고 npm 설치
RUN mkdir -p /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# 소스를 작업폴더로 복사
COPY . /app/
CMD ["npm", "start"]

# docker build -f Dockerfile-dev -t mydev .
# docker run -it -p 1024:3000 mydev
